site_name: Mkdocs try
theme:
  name: material
  custom_dir: overrides
  
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fdecharlet
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/florian-charlet/


copyright: |
  &copy; 2023 <a href="https://github.com/fdecharlet"  target="_blank" rel="noopener">Florian Charlet</a>


repo_url: https://github.com/fdecharlet/mkdocs-website
repo_name: fdecharlet/mkdocs-website

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
   - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

